export const FIM_COMMAND_NAME = {
  addTests: "fim.addTests",
  addTypes: "fim.addTypes",
  conversationHistory: "fim.conversationHistory",
  disable: "fim.disable",
  enable: "fim.enable",
  review: "fim.review",
  explain: "fim.explain",
  focusSidebar: "fim.sidebar.focus",
  generateDocs: "fim.generateDocs",
  getGitCommitMessage: "fim.getGitCommitMessage",
  hideBackButton: "fim.hideBackButton",
  manageProviders: "fim.manageProviders",
  newConversation: "fim.newConversation",
  openPanelChat: "fim.openPanelChat",
  openChat: "fim.openChat",
  refactor: "fim.refactor",
  settings: "fim.settings",
  stopGeneration: "fim.stopGeneration",
  templateCompletion: "fim.templateCompletion",
  fimSymmetryTab: "fim.symmetry",
  addFileToContext: "fim.addFileToContext",
  getContextFiles: "fim.getContextFiles",
  addSelectionToContext: "fim.addSelectionToContext"
}
