export const FIM_TEMPLATE_FORMAT = {
  automatic: "automatic",
  custom: "custom-template",
  deepseek: "deepseek"
}

export const STOP_DEEPSEEK = [
  "<｜fim▁begin｜>",
  "<｜fim▁hole｜>",
  "<｜fim▁end｜>",
  "<END>",
  "<｜end of sentence｜>"
]

export const WASM_LANGUAGES: { [key: string]: string } = {
  "php-s": "php",
  bash: "bash",
  c: "c",
  cc: "cpp",
  cjs: "javascript",
  cpp: "cpp",
  cs: "c_sharp",
  css: "css",
  cts: "typescript",
  cxx: "cpp",
  eex: "embedded_template",
  el: "elisp",
  elm: "elm",
  emacs: "elisp",
  erb: "ruby",
  ex: "elixir",
  exs: "elixir",
  go: "go",
  h: "c",
  heex: "embedded_template",
  hpp: "cpp",
  htm: "html",
  html: "html",
  hxx: "cpp",
  java: "java",
  js: "javascript",
  json: "json",
  jsx: "javascript",
  leex: "embedded_template",
  lua: "lua",
  mjs: "javascript",
  ml: "ocaml",
  mli: "ocaml",
  mts: "typescript",
  ocaml: "ocaml",
  php: "php",
  php3: "php",
  php4: "php",
  php5: "php",
  php7: "php",
  phps: "php",
  phtml: "php",
  py: "python",
  pyi: "python",
  pyw: "python",
  ql: "ql",
  rb: "ruby",
  rdl: "systemrdl",
  res: "rescript",
  resi: "rescript",
  rs: "rust",
  sh: "bash",
  toml: "toml",
  ts: "typescript",
  tsx: "tsx",
  vue: "vue"
}
